version: "3"
services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swaggerui
    ports:
      - "80:8080"
    volumes:
      - ./app/oas:/usr/share/nginx/html/oas/
      - ./5-addMockServerUrl.sh:/docker-entrypoint.d/5-addMockServerUrl.sh
      - ./.env:/.env
    env_file:
      - ./.config
  proxy:
    image: caddy
    container_name: proxy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8080:80"
