openapi: 3.1.0
info:
  title: ExampleApi1
  description: Test
  version: 0.0.1
  contact:
    name: ExampleApi1
    email: open@api.com
servers:
  - url: http://0.0.0.0:8080/ExampleApi1
tags:
  - name: data-point
    description: <SchemaDefinition schemaRef="#/components/schemas/DataPoint" />
    x-displayName: DataPoint
  - name: response
    description: <SchemaDefinition schemaRef="#/components/schemas/MetricResponse" />
    x-displayName: MetricResponse
  - name: agregation-types
    description: <SchemaDefinition schemaRef="#/components/schemas/MetricResponse" />
    x-displayName: AgregationTypesResponse
  - name: error-response
    description: <SchemaDefinition schemaRef="#/components/schemas/ErrorResponse" />
    x-displayName: ErrorResponse
paths:
  /metric:
    get:
      summary: Summary
      description: Description
      tags:
        - data-point
      operationId: dataPointsByMetrics
      parameters:
        - name: type
          in: query
          description: "`required`. Specify the type of metric the data points should be retrieved to"
          required: true
          schema:
            type: string
            enum:
              - df
              - mltc
              - cfr
              - mttr
        - name: from
          in: query
          description: "`required`. Date/time from when the results should be filtered. Should be before the 'to' param, and should always be paired with the 'to' param."
          required: true
          schema:
            type: string
            format: date-time
            example: "2020-01-01T00:00:00Z"
        - name: to
          in: query
          description: "`required`. Date/time to when the results should be filtered. Should be before the current date/time and after the 'from' param, and should always be paired with the 'from' param."
          required: true
          schema:
            type: string
            format: date-time
            example: "2020-01-31T23:59:59Z"
        - name: aggregation
          in: query
          description: "`optional`. Specify how the data points should be aggregated. If not informed, it will default to `weekly`"
          schema:
            type: string
            enum:
              - weekly
              - monthly
              - quarterly
            default: weekly
        - name: x-correlation-id
          in: header
          description: Unique identifer associated with the request
          schema:
            type: string
            format: uuid
          example: c0c62604-e3ab-4008-b882-4effcb4963ae
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MetricResponse"
          headers:
            x-correlation-id:
              description: Unique identifer associated with the request
              schema:
                type: string
                format: uuid
              example: c0c62604-e3ab-4008-b882-4effcb4963ae
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          headers:
            x-correlation-id:
              description: Unique identifer associated with the request
              schema:
                type: string
                format: uuid
              example: c0c62604-e3ab-4008-b882-4effcb4963ae
        "401":
          description: Unauthorized! Should Provide a valid JWT token
          content: {}
          headers:
            x-correlation-id:
              description: Unique identifer associated with the request
              schema:
                type: string
                format: uuid
              example: c0c62604-e3ab-4008-b882-4effcb4963ae
        "403":
          description: Forbidden! Access denied. Do not have authority to call this API
          content: {}
          headers:
            x-correlation-id:
              description: Unique identifer associated with the request
              schema:
                type: string
                format: uuid
              example: c0c62604-e3ab-4008-b882-4effcb4963ae
        "500":
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                message: Failed to connect to DevLake's DB
                reference: c0c62604-e3ab-4008-b882-4effcb4963ae
          headers:
            x-correlation-id:
              description: Unique identifer associated with the request
              schema:
                type: string
                format: uuid
              example: c0c62604-e3ab-4008-b882-4effcb4963ae
  /aggregation:
    get:
      summary: Get agregation types
      description: Get agregation types
      tags:
        - agregation-types
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AgregationTypesResponse"
          headers:
            x-correlation-id:
              description: Unique identifer associated with the request
              schema:
                type: string
                format: uuid
              example: c0c62604-e3ab-4008-b882-4effcb4963ae
      operationId: get-aggregation
components:
  schemas:
    DataPoint:
      type: object
      x-examples:
        Example 1:
          - key: 1
            count: 3
            average: 3
      properties:
        key:
          type: integer
          minimum: 1
          maximum: 52
        count:
          type: integer
          minimum: 1
          maximum: 150
        average:
          type: integer
          minimum: 1
          maximum: 150
    AgregationType:
      type: object
      properties:
        t:
          type: string
    MetricResponse:
      type: array
      items:
        $ref: "#/components/schemas/DataPoint"
    AgregationTypesResponse:
      type: array
      items:
        $ref: "#/components/schemas/AgregationType"
    ErrorResponse:
      required:
        - message
        - reference
      type: object
      properties:
        message:
          title: Generic information about the failure
          type: string
          example: "You have requested an unsupported metric name, please check the metric parameter"
        reference:
          title: Generated ID to be able to trace more information about the error in the logs
          type: string
          example: c0c62604-e3ab-4008-b882-4effcb4963ae
